language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - '10'
  - '11'
  - '8'
  - '6'
stages:
  - test
  - name: deploy
    if: branch = master AND type = push
jobs:
  include:
    - stage: test
      script:
        - npm run test:prod
    - stage: test
      script:
        - npm run build
    - stage: deploy
      name: 'Deploy to NPM'
      script:
        - npm run semantic-release
      env:
        - NODE_ENV=production
